### PR TITLE
add drag handlers for circle and rectangle. update example.

### PR DESCRIPTION
**Pull request by dremonkey**
Takes the work you did for poly and extends it to circle and rectangle, making the need for the center drag marker moot.

### CODE REVIEW

**Comment by dremonkey** [comment]
Also repositioning the circle will not actually work until this pull request https://github.com/w8r/Leaflet.Path.Drag/pull/4 has been merged.

**Comment by w8r** [comment]
I'm not so sure about that. The thing is I wanted the thing to be as little intrusive as possible, only adding  behaviour to Leaflet.draw, not changing any of the existing. Drag handles for Circle and Rectangle are already there, and I know why: it's easy to transform these and there's no problem getting the shape's center of mass. 

I think this plugin just has to be the part of Leaflet.draw, at some point people will request resizing, skewing an rotation as well, if they didn't already. I tried to raise the point in Leaflet.draw issues, but didn't get any attention, so I might create a PR to make them adopt that.

**Comment by dremonkey** [comment]
That makes sense. For my use case, we want consistent handling for all the
shapes so I went ahead a made the changes to circle and rectangle, but I
understand that it might not make sense to merge it into what you are doing
especially since you are trying to get your changes merged with
Leaflet.draw. And I agree... your plugin should be part of Leaflet.draw.

**Comment by w8r** [comment]
Or...maybe you're right, if that's not going to merged in this state, why not just add ability to drag circles not only by the handle marker, but using the whole path. If you update your fork once again(sorry, I made some changes to update L.Path.Drag) - I'll merge that. Otherwise you can use your fork just as well.

**Comment by w8r** [comment]
and see, I removed the development info

**Comment by dremonkey** [comment]
gonna close this and open a new one then

**Pull request closed without merging**
