### PR TITLE
Compatible with draw 0.4.x

### PR DESCRIPTION
**Pull request by bhaskarvk**
I tested out the leaflet-draw-0.4 branch, and it's still not compatible with leaflet-draw 0.4, I got JS errors when moving/resizing polygons/polylines. I made some bare minimum changes to the master branch to make it compatible with leaflet-draw 0.4, and so far everything works. Please check my changes and let me know if I'm missing anything.

### CODE REVIEW

**Comment by w8r** [comment]
Thanks a lot for your work! My frail attempts to make it work with leaflet-draw-0.4 are in the branch leaflet-draw-0.4, maybe it will help as well. I will try your PR out

**Comment by bhaskarvk** [comment]
You are welcome! I did try out the leaflet-draw-0.4 branch but got JS errors when moving/resizing polygons/polylines, hence my changes. I do see that you've done some extra work in the leaflet-draw-0.4 branch for getting coordinates, so may be the best solution is to combine my branch with your branch. Thanks again.

**Comment by w8r** [comment]
Oh, sorry, I misread that. Yes, I will!

**Comment by bhaskarvk** [comment]
I added one small fix which allows you to disable just the edit part of the edit toolbar.

**Comment by bhaskarvk** [comment]
One more thing, even with this fix, one thing that does not work as of yet, is the customization of paths using the 'selectedPathOptions' argument.

**Comment by bhaskarvk** [comment]
OK I fixed the 'selectPathOptions' too. Now AFAIK this is fully compatible w/ leaflet-draw 0.4 release.

**Comment by w8r** [comment]
@bhaskarvk thank you so much! I only fixed the demo and the array depth in polygons - that's `leaflet@1.0` compatibility

**Comment by bhaskarvk** [comment]
Thanks for merging my PR. Btw my PR was also compatible w/ leaflet 0.7 + leaflet.draw 0.4. So if you want you can also merge it w/ the leaflet-0.7 branch, to bring latest leaflet.draw & laeaflet.draw.drag to 0.7 branch too.

Thanks!

**Pull request merged**
