### PR TITLE
Feature/draw 0.4

### PR DESCRIPTION
**Pull request by bhaskarvk**
Thanks for merging this with Master, please also merge with leaflet-0.7 branch as leaflet.draw 0.4 is also compatible with leaflet 0.7.x. So it makes sense to have a 0.7.x compatible ver. of this plugin too.

### CODE REVIEW

**Comment by bhaskarvk** [comment]
Hi any interest in merging this PR for supporting Leaflet.Draw.Drag in Leaflet 0.7?

**Comment by w8r** [comment]
Sorry for missing this one, is it backward-compatible with 0.2? Did you try it? I am a bit short for time at the moment

**Comment by bhaskarvk** [comment]
I haven't checked with backward compatibility with 0.2, but FWIW leaflet.draw 0.4 works with leaflet 0.7, so I don't think backward compatibility with 0.2 is an issue.

**Comment by bhaskarvk** [comment]
Friendly ping!

**Pull request closed without merging**
